'use client'
import { Metadata } from 'next'

import { ToggleThemeButton } from '@/components/Button/ToggleThemeButton'

import { auth } from '@/services/firebase/app'
import { signIn } from '@/services/firebase/auth'

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
}

export default function Home() {
	async function doisA() {
		await signIn()
	}

	function getUser() {
		console.log(auth.currentUser)
	}

	return (
		<>
			<button onClick={doisA}>Hellow</button>
			<button onClick={() => auth.signOut()}>SignOut</button>
			<button onClick={() => getUser()}>Get User</button>

			<ToggleThemeButton />
		</>
	)
}
