'use client'
import { Metadata } from 'next'

import { ToggleThemeButton } from '@/components/Button/ToggleThemeButton'

import { useAuth } from '@/providers/AuthProvider'

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
}

export default function Home() {
	const { currentUser, login, logout } = useAuth()
	return (
		<>
			<button onClick={login}>Sign In</button>
			<button onClick={logout}>SignOut</button>
			<p>{currentUser?.displayName || 'No user is logged'}</p>

			<ToggleThemeButton />
		</>
	)
}
