import { Metadata } from 'next'

import { ToggleThemeButton } from '@/components/Button/ToggleThemeButton'

// import { Stack } from '@chakra-ui/react'

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
}

export default function Home() {
	return (
		// <Stack>
		<ToggleThemeButton />
		// </Stack>
	)
}
